apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicationset
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
        type: front-end
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
     containers:
       - name: myapp-pod
         image:  nginx
         resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
