apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-controller
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"