apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end-rc
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp-pod
        type: front-end-pod
    spec:
      containers:
        - name: myapp-pod
          image:  nginx
  replicas: 3